import type { Metadata } from "next";
import { Geist_Mono, IBM_Plex_Sans, Space_Grotesk } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

// Reverted back to IBM Plex Sans with all weights and styles
const phi = IBM_Plex_Sans({
  variable: "--font-phi",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const iota = Space_Grotesk({
  variable: "--font-iota",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "IPHIPI Global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${phi.variable} ${iota.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body 
        className="font-sans min-h-full flex flex-col"
        /* Keeping the inline style to ensure the font applies globally without relying on Tailwind */
        style={{ fontFamily: "var(--font-phi), sans-serif" }}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}